version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3

jobs:
  console-log:
    docker:
    - image: ariv3ra/terraform-gcp:tf-v0.14.2
    steps:
      - run: echo $CIRCLE_CONTINUATION_KEY




workflows:
  check-updated-files:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            .* continuation_key $CIRCLE_CONTINUATION_KEY
            app/src1/.* build-src-1 true
            app/src2/.* build-src-2 true
          base-revision: main
          config-path: .circleci/continue_pipeline.yml