version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3


jobs:
  console-log:
    docker:
    - image: ariv3ra/terraform-gcp:tf-v0.14.2
    steps:
      - run: echo $CIRCLE_CONTINUATION_KEY

workflows:
  check-updated-files:
    jobs:
      - console-log
      - path-filtering/filter:
          name: check-updated-files1
          mapping: |
            app/src1/.* build-src-1 true
          base-revision: main
          config-path: .circleci/config-1.yml
      - path-filtering/filter:
          name: check-updated-files2
          requires:
            - check-updated-files1
          mapping: |
            app/src2/.* build-src-2 true
          base-revision: main
          config-path: .circleci/config-2.yml