version: 2.1

setup: true

jobs:
  console-log:
    docker:
      - image: ariv3ra/terraform-gcp:tf-v0.14.2
    steps:
      - run: echo KAK


workflows:
  approve-poc:
    jobs:
      - approve-me:
          context: approver
          type: approval
      - console-log:
          name: nothings
          requires:
            - approve-me
          