version: 2.1

setup: true

jobs:
  console-log:
    docker:
    - image: ariv3ra/terraform-gcp:tf-v0.14.2
    steps:
      - run: echo $CIRCLE_CONTINUATION_KEY

workflows:
  check-updated-files:
    jobs:
      - console-log