version: 2.1

orbs:
  continuation: circleci/continuation@0.3.1


parameters:
  build-src-1:
    type: boolean
    default: false
  build-src-2:
    type: boolean
    default: false  

workflows:
  src1:
    when: << pipeline.parameters.build-src-1 >>
    jobs:
      - continuation/continue:
          name: cosigner-infrastructure
          configuration_path: .circleci/config-1.yml
  src2:
    when: << pipeline.parameters.build-src-2 >>
    jobs:
      - approve-poc2:
          type: approval