version: 2.1

parameters:
  build-src-1:
    type: boolean
    default: false
  build-src-2:
    type: boolean
    default: false  
  continuation-key:
    type: string

jobs:
  console-log:
    docker:
    - image: ariv3ra/terraform-gcp:tf-v0.14.2
    steps:
      - run: echo << pipeline.parameters.continuation-key >>


workflows:
  src1:
    # when: << pipeline.parameters.build-src-1 >>
    jobs:
      - console-log:
          name: kak
      - approve-poc1:
          type: approval
  src2:
    when: << pipeline.parameters.build-src-2 >>
    jobs:
      - approve-poc2:
          type: approval