version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

    
workflows:
  check-updated-files:
    jobs:
      - continuation/continue:
          name: build-src-1
          configuration_path: .circleci/config-1.yml
      - continuation/continue:
          name: build-src-2
          configuration_path: .circleci/config-2.yml
    
